a=input("enter value a:")
b=input("enter value b:")
print(int(a)+int(b))
a=input("enter value a:")
b=input("enter value b:")
print(float(a)+float(b))
a=input("enter value a:")
b=input("enter value b:")
print(eval(a)+eval(b))
